apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: 730335201364.dkr.ecr.us-east-1.amazonaws.com/super30_ecr_registry_1:8
      imagePullSecrets:
        - name: ecr-registry
