apiVersion: apps/v1
kind: Deployment
metadata:
  name: vg-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: vg-argo1
  template:
    metadata:
      labels:
        app: vg-argo1
    spec:
      containers:
      - image: nginx
        name: vg-argo1
        ports:
        - containerPort: 80
